### ISSUE TITLE
Invalid flagging of faulty `...` usage

### ISSUE THREAD

**Issue by DavisVaughan** [HenrikBengtsson/globals#62]
purrr anonymous functions use `...` as a catch all. It looks odd to have `...` inside the RHS of the `~`, but this eventually evaluates as something meaningful, so it would be awesome if future could allow this to go through.

``` r
library(purrr)
library(future)

catcher <- function(x) {
  map(x, ~list(...))
}

catcher(list(1:2, 1:3))
#> [[1]]
#> [[1]][[1]]
#> [1] 1 2
#> 
#> 
#> [[2]]
#> [[2]][[1]]
#> [1] 1 2 3

future({
  catcher(list(1:2, 1:3))
})
#> Error in getGlobalsAndPackages(expr, envir = envir, tweak = tweakExpression, : Did you mean to create the future within a function?  Invalid future expression tries to use global '...' variables that do not exist: {; catcher(list(1:2, 1:3)); }
```

<sup>Created on 2020-08-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

See also, https://github.com/DavisVaughan/furrr/issues/114

**Comment by HenrikBengtsson** [comment]
Problem to be solved: Allow for ellipsis in formulas, e.g.

```r
> globals::findGlobals(list(..., ..3) ~ list(., .x, ..., ..1, ..2))
[1] "~"    "list" "."    ".x"   "..." 
Warning messages:
1: <anonymous>: ... may be used in an incorrect context: 'list(..., ..3)'
 
2: <anonymous>: ..3 may be used in an incorrect context
 
3: <anonymous>: ... may be used in an incorrect context: 'list(., .x, ..., ..1, ..2)'
 
4: <anonymous>: ..1 may be used in an incorrect context
 
5: <anonymous>: ..2 may be used in an incorrect context
```

**Comment by HenrikBengtsson** [comment]
This has been fixed in the develop branch.  I'm running another round of revdep on 181 packages - I'll reopen if it there are any issues

**Comment by DavisVaughan** [comment]
Thank you for all the work here!

**Comment by HenrikBengtsson** [comment]
Thanks for your detailed reports and troubleshooting.

The revdep checks worked out

**Comment by Yue-Jiang** [comment]
Apologies if I missed something, should I expect with the current version of {globals} the example at the beginning of this thread can go through? Asking because I still see it reporting the same error, with R 4.0.2, globals 0.14.0.9000, future 1.21.0, purrr 0.3.4. Thanks a lot!

```
library(purrr)
library(future)

catcher <- function(x) {
  map(x, ~list(...))
}

catcher(list(1:2, 1:3))
#> [[1]]
#> [[1]][[1]]
#> [1] 1 2
#> 
#> 
#> [[2]]
#> [[2]][[1]]
#> [1] 1 2 3

future({
  catcher(list(1:2, 1:3))
})
```

`Error in getGlobalsAndPackages(expr, envir = envir, tweak = tweakExpression,  : 
  Did you mean to create the future within a function?  Invalid future expression tries to use global '...' variables that do not exist: {; catcher(list(1:2, 1:3)); }`
