### ISSUE TITLE
Error with `purrr::partial()` function

### ISSUE THREAD

**Issue by DavisVaughan** [HenrikBengtsson/globals#63]
I see this with globals 0.13.0

``` r
fn <- function(x) sum(x, na.rm = TRUE)
x <- c(NA, 1, 2)
fn_partial <- purrr::partial(fn, x = x)

globals::globalsOf(fn_partial)
#> Error in globalsByName(names, envir = envir, mustExist = mustExist): Identified global objects via static code inspection (structure(function (...); {; env_bind(mask, ... = env_get(current_env(), "...")); eval_tidy(call, mask); }, class = c("purrr_function_partial", "function"), body = ~(function (x); sum(x, na.rm = TRUE))(x = x, ...), fn = fn)). Failed to locate global object in the relevant environments: 'env_bind'
```

---

This actually came up in a furrr test that I have that seems to fail now (it might only be in the dev version of furrr that this fails).

This works with globals 0.12.5:

``` r
library(furrr)
library(purrr)
plan(sequential)

fn <- function(x) sum(x, na.rm = TRUE)

x <- list(c(1, 2, NA), c(2, 3, 4))

fns1 <- map(x, ~ purrr::partial(fn, x = .x))

future_map_dbl(fns1, ~.x())
#> [1] 3 9
```

But with globals 0.13.0:

``` r
library(furrr)
library(purrr)
plan(sequential)

fn <- function(x) sum(x, na.rm = TRUE)

x <- list(c(1, 2, NA), c(2, 3, 4))

fns1 <- map(x, ~ purrr::partial(fn, x = .x))

future_map_dbl(fns1, ~.x())
#> Error in future::getGlobalsAndPackages(expr = chunk_args, envir = env_globals, : Did you mean to create the future within a function?  Invalid future expression tries to use global '...' variables that do not exist: list(structure(function (...); {; env_bind(mask, ... = env_get(current_env(), "...")); eval_tidy(call, mask); }, class = c("purrr_function_partial", "function"), body = ~(function (x); sum(x, na.rm = TRUE))(x = .x, ...), fn = fn), structure(function (...); ...; eval_tidy(call, mask); }, class = c("purrr_function_partial", "function"), body = ~(function (x); sum(x, na.rm = TRUE))(x = .x, ...), fn = fn))
```

**Comment by HenrikBengtsson** [comment]
First, I'm pretty sure:

```r
> sum2 <- purrr::partial(sum)
> globals::globalsOf(sum2)
Error in globalsByName(names, envir = envir, mustExist = mustExist) : 
Identified global objects via static code inspection (structure(function (...); {; env_bind(mask, ... = 
env_get(current_env(), "...")); eval_tidy(call, mask); }, class = c("purrr_function_partial", "function"), 
body = ~(function (...,; na.rm = FALSE); .Primitive("sum")(..., na.rm = na.rm))(...), fn = sum)). Failed to 
locate global object in the relevant environments: 'env_bind'
```

should be right.  To avoid this, one need make sure `env_bind` etc. are defined, or pass `mustExist = FALSE`.

                                                                         
Now, that you get:

```r
> fcns <- purrr::map(x, ~ purrr::partial(sum))
> y <- furrr::future_map_dbl(fcns, ~.x())
Error in future::getGlobalsAndPackages(expr = chunk_args, envir = env_globals,  :
  Did you mean to create the future within a function?  Invalid future
expression tries to use global '...' variables that do not exist:
list(structure(function (...); {; env_bind(mask, ... = env_get(current_env(),
"...")); eval_tidy(call, mask); }, class = c("purrr_function_partial",
"function"), body = ~(function (...,; na.rm = FALSE); ...; }, class =
c("purrr_function_partial", "function"), body = ~(function (...,; na.rm =
FALSE); .Primitive("sum")(..., na.rm = na.rm))(...), fn = sum))
```

seems like a valid problem.  I need to figure out if this should be fixed in **globals** or **future**.

**Comment by HenrikBengtsson** [comment]
Here's a simplied reproducible example:

```r
x <- c(1:100, NA)
sum2 <- purrr::partial(sum, na.rm = TRUE)
fcns0 <- purrr::map(list(sum2), identity)
fcns0[[1]](x)
## [1] 5050
```

```r
fcns1 <- furrr::future_map(list(sum2), identity)
# Error in future::getGlobalsAndPackages(expr = chunk_args, envir = env_globals,  : 
#   Did you mean to create the future within a function?  Invalid future expression tries to use global '...' variables that do not exist: list(structure(function (...); {; env_bind(mask, ... = env_get(current_env(), "...")); eval_tidy(call, mask); }, class = c("purrr_function_partial", "function"), body = ~(function (...,; na.rm = FALSE); .Primitive("sum")(..., na.rm = na.rm))(...), fn = sum))
```



Note that the following works:

```r
fcns2 <- future.apply::future_lapply(list(sum2), identity)
stopifnot(all.equal(fcns2, fcns0))
fcns2[[1]](x)
## [1] 5050
```

**Comment by HenrikBengtsson** [comment]
So, this might be an issue with your devel version of **furrr**.  I'll remove the 'bug' label here but leave it open until you had a chance to investigate more.

**Comment by DavisVaughan** [comment]
I believe it is still an issue with either globals or future.

The issue stems from the environment that is being searched in for globals. I believe we spoke about the fact that devel furrr now uses the parent frame as the environment to search for globals of `x` and `...` in (this is the new `env_globals` argument in each furrr function). I am fairly confident that this is correct. future.apply still uses the current frame, as seen here https://github.com/HenrikBengtsson/future.apply/blob/65b1cfa8ed4f0648922f4c7b1659c1958be2ceaf/R/future_lapply.R#L154-L161

The below example hopefully makes things a little clearer. When we search for globals in `x`, which contains a function with `...` in its signature, if `...` aren't in the `envir` then we seem to get the error. When `envir` is the current frame AND when that frame is inside a function with `...` in its signature (like `future_lapply()`) then we don't get the error. I think this is just by a bit of luck?

```r
sum2 <- purrr::partial(sum, na.rm = TRUE)
x <- list(sum2)

# note that the function in here has `...` in its argument list
x
#> [[1]]
#> <partialised>
#> function (...) 
#> sum(na.rm = TRUE, ...)

parent_frame_no_dots <- function(x) {
  envir <- parent.frame()
  future::getGlobalsAndPackages(x, envir = envir)
}
current_frame_no_dots <- function(x) {
  envir <- environment()
  future::getGlobalsAndPackages(x, envir = envir)
}
parent_frame_with_dots <- function(x, ...) {
  envir <- parent.frame()
  future::getGlobalsAndPackages(x, envir = envir)
}
current_frame_with_dots <- function(x, ...) {
  envir <- environment()
  future::getGlobalsAndPackages(x, envir = envir)
}

parent_frame_no_dots(x)
#> Error in future::getGlobalsAndPackages(x, envir = envir): Did you mean to create the future within a function?  Invalid future expression tries to use global '...' variables that do not exist: list(structure(function (...); {; env_bind(mask, ... = env_get(current_env(), "...")); eval_tidy(call, mask); }, class = c("purrr_function_partial", "function"), body = ~(function (...,; na.rm = FALSE); .Primitive("sum")(..., na.rm = na.rm))(na.rm = TRUE, ...), fn = sum))

current_frame_no_dots(x)
#> Error in future::getGlobalsAndPackages(x, envir = envir): Did you mean to create the future within a function?  Invalid future expression tries to use global '...' variables that do not exist: list(structure(function (...); {; env_bind(mask, ... = env_get(current_env(), "...")); eval_tidy(call, mask); }, class = c("purrr_function_partial", "function"), body = ~(function (...,; na.rm = FALSE); .Primitive("sum")(..., na.rm = na.rm))(na.rm = TRUE, ...), fn = sum))

# this is what furrr essentially does, which I am fairly confident is the
# correct env to look up the globals for `x` in
parent_frame_with_dots(x)
#> Error in future::getGlobalsAndPackages(x, envir = envir): Did you mean to create the future within a function?  Invalid future expression tries to use global '...' variables that do not exist: list(structure(function (...); {; env_bind(mask, ... = env_get(current_env(), "...")); eval_tidy(call, mask); }, class = c("purrr_function_partial", "function"), body = ~(function (...,; na.rm = FALSE); .Primitive("sum")(..., na.rm = na.rm))(na.rm = TRUE, ...), fn = sum))

# this is what future_apply does. The envir here happens to have `...` in it
# since `current_frame_with_dots()` has `...` in its signature,
# which means the search for globals in `x` doesn't fail when `x` has a function
# that has `...` in the signature
current_frame_with_dots(x)
#> $expr
#> {
#>     do.call(function(...) list(function (...) 
#>     {
#>         env_bind(mask, ... = env_get(current_env(), "..."))
#>         eval_tidy(call, mask)
#>     }), args = future.call.arguments)
#> }
#> 
#> $globals
#> $future.call.arguments
#> list()
#> attr(,"class")
#> [1] "DotDotDotList" "list"         
#> 
#> attr(,"where")
#> attr(,"where")$future.call.arguments
#> <environment: 0x7f842f384140>
#> 
#> attr(,"class")
#> [1] "FutureGlobals" "Globals"       "list"         
#> attr(,"resolved")
#> [1] FALSE
#> attr(,"total_size")
#> [1] 0
#> 
#> $packages
#> character(0)
```

**Comment by DavisVaughan** [comment]
I think I've isolated the bug without needing purrr.

Take this "partially" evaluated function

``` r
fn <- function(..., foo = TRUE) {
  list(..., foo = foo)
}

# Partially evaluate the call
fn_wrapped <- as.call(list(fn, foo = FALSE, quote(...)))

fn_wrapped
#> (function(..., foo = TRUE) {
#>   list(..., foo = foo)
#> })(foo = FALSE, ...)
```

If we try to detect globals of this thing, `globalsOf()` will warn and `getGlobalsAndPackages()` will error.

``` r
# globals and future see this and think it is a bug
globals::globalsOf(fn_wrapped, envir = globalenv())
#> Warning: <anonymous>: ... may be used in an incorrect context: 'FALSE(...)'
#> $`{`
#> .Primitive("{")
#> 
#> $list
#> function (...)  .Primitive("list")
#> 
#> $...
#> [1] NA
#> attr(,"class")
#> [1] "DotDotDotList" "logical"      
#> 
#> attr(,"class")
#> [1] "Globals" "list"   
#> attr(,"where")
#> attr(,"where")$`{`
#> <environment: base>
#> 
#> attr(,"where")$list
#> <environment: base>
#> 
#> attr(,"where")$...
#> NULL

future::getGlobalsAndPackages(fn_wrapped, envir = globalenv())
#> Error in future::getGlobalsAndPackages(fn_wrapped, envir = globalenv()): Did you mean to create the future within a function?  Invalid future expression tries to use global '...' variables that do not exist: (function (..., foo = TRUE); {; list(..., foo = foo); })(foo = FALSE, ...)
```

It is true that the `...` in this call aren't used in the right context if you just evaluate them in the global env (because there are no `...` there). However, purrr binds `...` into an environment and then evaluates the call in that environment, which makes the call valid.

``` r
# It is true that the `...` in this partial function don't normally work
eval(fn_wrapped)
#> Error in eval(fn_wrapped): '...' used in an incorrect context

# But you can make them work! This is essentially what purrr does
make_dots <- function(...) {
  environment()[["..."]]
}

env <- new.env(parent = baseenv())
env[["..."]] <- make_dots(x = 1)

# Look! Dots!
env$...
#> <...>

eval(fn_wrapped, env)
#> $x
#> [1] 1
#> 
#> $foo
#> [1] FALSE
```

**Comment by DavisVaughan** [comment]
Okay, I have more information! I think I have gotten to the root of this. This issue with purrr only happens because:

- purrr has an _attribute_ for globals to search called `body`

- `body` is a quosure, which is like a formula, and formulas get special handling by globals now. Specifically `dotdotdot` becomes hardcoded to `"return"` in `find_globals_ordered()` when you have a `~`. https://github.com/HenrikBengtsson/globals/blob/c9a514701b50c71f7328424664ff8affb69c3288/R/findGlobals.R#L110

- The RHS of that formula is a call with `...` in it - which we are expecting to get ignored because it is in an attribute. 

---

It looks like when `findGlobals()` searches attributes, it hardcodes `dotdotdot = "ignore"`, which seems great! That _should_ have made `purrr::partial()` work automatically. https://github.com/HenrikBengtsson/globals/blob/c9a514701b50c71f7328424664ff8affb69c3288/R/findGlobals.R#L333

However, it turns out that the dots are actually _not_ ignored when the attribute is a formula with `...` in it...which is exactly what purrr does. This is due to `find_globals_ordered()` hardcoding `dotdotdot = "return"` in its call to `call_find_globals_with_dotdotdot()` (the second bullet point from above), so dots don't get ignored as they should!

Here is a good non-purrr example:

``` r
fn <- call("fn", quote(...))

attr_fn <- fn
attr_fn_formula <- bquote(~ .(fn))

attr_fn
#> fn(...)
attr_fn_formula
#> ~fn(...)

# Put them in attributes - all dots should be ignored
x1 <- structure(1, fn = attr_fn)
x2 <- structure(1, fn = attr_fn_formula)


globals::globalsOf(x1, envir = globalenv(), dotdotdot = "ignore")
#> $fn
#> fn(...)
#> 
#> attr(,"class")
#> [1] "Globals" "list"   
#> attr(,"where")
#> attr(,"where")$fn
#> <environment: R_GlobalEnv>

# Dots are not "ignore"d! They are "return"ed!
globals::globalsOf(x2, envir = globalenv(), dotdotdot = "ignore")
#> $`~`
#> .Primitive("~")
#> 
#> $fn
#> fn(...)
#> 
#> $...
#> [1] NA
#> attr(,"class")
#> [1] "DotDotDotList" "logical"      
#> 
#> attr(,"class")
#> [1] "Globals" "list"   
#> attr(,"where")
#> attr(,"where")$`~`
#> <environment: base>
#> 
#> attr(,"where")$fn
#> <environment: R_GlobalEnv>
#> 
#> attr(,"where")$...
#> NULL

gp <- future::getGlobalsAndPackages(x1, envir = globalenv())

# The "return"ed dots causes the failure here!
gp <- future::getGlobalsAndPackages(x2, envir = globalenv())
#> Error in future::getGlobalsAndPackages(x2, envir = globalenv()): Did you mean to create the future within a function?  Invalid future expression tries to use global '...' variables that do not exist: structure(1, fn = ~fn(...))
```

<sup>Created on 2020-10-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by DavisVaughan** [comment]
Added #67 as a potential solution. Attributes with formulas containing dots are now correctly ignored

``` r
fn <- call("fn", quote(...))
attr_fn_formula <- bquote(~ .(call("fn", quote(...))))
x2 <- structure(1, fn = attr_fn_formula)
x2
#> [1] 1
#> attr(,"fn")
#> ~fn(...)

globals::findGlobals(x2, envir = globalenv(), dotdotdot = "return")
#> [1] "~"  "fn"
```

**Comment by HenrikBengtsson** [comment]
Running **globals** revdep checks on 1st and 2nd generation dependencies with PR #67 applied.  Will keep this issue open until all checks complete.

**Comment by HenrikBengtsson** [comment]
Revdep checks came back clean.  I'm ready to submit globals 1.13.1 to CRAN.  Could you please run revdep checks on your devel furrr with globals 1.13.0-9000 in the develop branch to make sure all things are correct now?

**Comment by DavisVaughan** [comment]
Looks good to me:

- All builds are passing with dev globals https://github.com/DavisVaughan/furrr/actions/runs/300737069

- Revdeps of furrr were run with dev globals with no failures https://github.com/DavisVaughan/furrr/commit/14afb18fa01dc15149d3a017c74994ab6ea3b418
